language: php

php:
    - 5.4
    - 5.5
    - 5.6
    
before_install:
    - uname -a
    - php -i|grep Thread

install:
    - sudo apt-get install gearman-job-server 
    - sudo pecl install gearman

script: php -r '$c = new GearmanClient();$c->addServer();$c->doBackground("reverse", "Hello!");';
