language: php

php:
    - hhvm-nightly

install:
    - git clone https://github.com/mongofill/mongofill-hhvm
    - cd mongofill-hhvm
    - ./build.sh
    - cd ..

script:
    - cat /etc/hhvm/config.hdf
