sudo: required

language: bash

services:
  - docker

env:
  - PHP_VERSION=5.4
  - PHP_VERSION=5.5
  - PHP_VERSION=5.6
  - PHP_VERSION=7.0

before_install:
  - docker --version
  - docker pull tarantool/tarantool
  - docker pull php
#  - composer require phpunit/phpunit

#install:
#  - composer install

before_script:
    # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )

  - docker run -it -d -P --name tarantool -v $(pwd):/app tarantool/tarantool
  - docker exec tarantool script /dev/null -c 'sudo cp /app/instance.lua /etc/tarantool/instances.enabled'
  - docker exec tarantool script /dev/null -c 'sudo tarantoolctl start instance'
  - docker exec tarantool script /dev/null -c 'for i in `seq 1 10`; do if sudo tarantoolctl status instance; then break; fi; sleep 1; done'

script:
  - docker run -it --rm --name my-php-script -v $(pwd):/app -w /app php:"$PHP_VERSION-cli" php test.php
