language: bash

before_install:
    - curl http://tarantool.org/dist/public.key | sudo apt-key add -
    - echo "deb http://tarantool.org/dist/1.6/ubuntu `lsb_release -c -s` main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
    - sudo apt-get update

install:
    - sudo apt-get -y install tarantool

before_script:
    - sudo cp ./instance.lua /etc/tarantool/instances.enabled
    - sudo tarantoolctl start instance
    - >
        for i in `seq 1 20`; do
            if sudo tarantoolctl status instance; then
                break;
            fi;
            sleep 1;
        done

script: 
    - ps aux | grep taran
    - tarantool --version
    - strace -f sudo tarantoolctl start instance
