language: php

php:
    - hhvm-nightly
    
before_install:
    # hphpize
    # https://github.com/facebook/hhvm/wiki/building-and-installing-hhvm-on-ubuntu-12.04
    ->
        bash -c 'if [[ $TRAVIS_PHP_VERSION == hhvm* ]]; then
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
        sudo add-apt-repository ppa:mapnik/boost -y;
        sudo apt-get update;
        
        sudo apt-get -y install gcc-4.8 g++-4.8;

        sudo apt-get -y install hhvm-dev;
        fi;'
        
install:
    - uname -a

    # hhvm-pgsql
    - >
        bash -c 'if [[ $TRAVIS_PHP_VERSION == hhvm* ]]; then
        git clone https://github.com/PocketRent/hhvm-pgsql.git;
        cd hhvm-pgsql;
        hphpize;
        cmake .;
        make;
        echo "hhvm.dynamic_extension_path = `pwd`" | sudo tee -a /etc/hhvm/php.ini;
        echo "hhvm.dynamic_extensions[pgsql] = pgsql.so" | sudo tee -a /etc/hhvm/php.ini;
        fi;'

script:
    - hhvm --version
