language: php

php:
    - hhvm-nightly

install:
    - lsb_release -a

    # hhvm-pgsql
    - >
        bash -c 'if [[ $TRAVIS_PHP_VERSION == hhvm* ]]; then
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        sudo apt-get update;
        sudo apt-get install libstdc++6-4.7-dev;
        wget https://raw.githubusercontent.com/PocketRent/hhvm-pgsql/releases/3.6.0/ubuntu/precise/pgsql.so;
        echo "hhvm.dynamic_extension_path = `pwd`" | sudo tee -a /etc/hhvm/php.ini;
        echo "hhvm.dynamic_extensions[pgsql] = pgsql.so" | sudo tee -a /etc/hhvm/php.ini;
        fi;'

script:
    - hhvm --version
