language: php

php:
    - 7.0

install:
    - composer global require phpunit/phpunit-mock-objects:3.0.*@dev
    - composer global require sebastian/resource-operations:1.0.*@dev
    - composer global require phpunit/phpunit:5.0.*@dev
    - export PATH="~/.composer/vendor/bin:$PATH"

script:
    - phpunit test.php
