language: php

php:
    - 5.4
    - 5.5
    - 5.6
    
before_install:
    - uname -a
    - php -i|grep Thread
    - wget http://tarantool.org/dist/public.key && sudo apt-key add ./public.key && release=`lsb_release -c -s` && echo "deb http://tarantool.org/dist/stable/ubuntu/ $release main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list && echo "deb-src http://tarantool.org/dist/stable/ubuntu/ $release main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
    - sudo apt-get update
    
install:
    - sudo apt-get install tarantool tarantool-client
    - sudo wget https://raw.githubusercontent.com/tarantool/queue/master/init.lua -O /usr/share/tarantool/lua/init.lua
    - sudo wget https://raw.githubusercontent.com/tarantool/queue/master/tarantool.cfg -O /etc/tarantool/instances.enabled/queue.cfg
    - sudo service tarantool restart
    - git clone https://github.com/tarantool/tarantool-php.git
    - cd ./tarantool-php
    - phpize --clean
    - phpize
    - ./configure
    - make
    - sudo make install

script: php -i
