language: php

php:
    - hhvm
    - hhvm-nightly
    
before_install:
    - sudo apt-get install hhvm-dev

install:
    - lsb_release -a

    # hhvm-pgsql
    - >
        bash -c 'if [[ $TRAVIS_PHP_VERSION == hhvm* ]]; then
        git clone https://github.com/reeze/msgpack-hhvm;
        cd msgpack-hhvm;
        hphpize && cmake . && make;
        echo "hhvm.dynamic_extension_path = `pwd`" | sudo tee -a /etc/hhvm/php.ini;
        echo "hhvm.dynamic_extensions[msgpack] = msgpack.so" | sudo tee -a /etc/hhvm/php.ini;
        fi;'

script:
    - hhvm --version
