language: php

php:
    - 7.0

install:
    - git clone https://github.com/msgpack/msgpack-php.git
    - cd msgpack-php
    - git checkout php7
    - phpize && ./configure
    - make
    - sudo make install
    - cd ..
    - printf "extension = msgpack.so\n" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini

script:
    - php test.php
