language: php

php:
    - 5.5

before_install:
    - uname -a

install: 
    - >
        bash -c 'if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then echo 1 && 
        echo 2; fi;'
    - >
        bash -c 'if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then 
        echo 4; 
        echo 2; 
        fi;'

script:
    - mysql --version
