language: php

php:
    - 5.4
    - 5.5
    - 5.6
    
before_install:
    - uname -a
    - php -i|grep Thread

install:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository -y ppa:gearman-developers/ppa
    - sudo apt-get update
    - sudo apt-get install gearman-job-server libgearman-dev
    - pecl install gearman
    - sudo service gearman-job-server restart

script: (nohup php worker.php >> worker.log 2>&1 &) && (nohup php worker.php >> worker.log 2>&1 &) && (php client.php)
