language: php

php:
    - 5.4
    - 5.5
    - 5.6
    
before_install:
    - uname -a

install:
    - > bash -c 'if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then echo 1 && \
        echo 2; fi;'

script: php -v
