language: php

php:
    - hhvm-nightly

install:
    - uname -a

    # hhvm-pgsql
    - >
        bash -c 'if [[ $TRAVIS_PHP_VERSION == hhvm* ]]; then
        sudo apt-get -y insall hhvm-dev;
        git clone https://github.com/PocketRent/hhvm-pgsql.git;
        cd hhvm-pgsql;
        hphpize;
        cmake .;
        make;
        echo "hhvm.dynamic_extension_path = `pwd`" | sudo tee -a /etc/hhvm/php.ini;
        echo "hhvm.dynamic_extensions[pgsql] = pgsql.so" | sudo tee -a /etc/hhvm/php.ini;
        fi;'

script:
    - hhvm --version
